
version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: daim
      POSTGRES_PASSWORD: daim
      POSTGRES_DB: daimpost
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
